// You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.
// Note: You may assume that at most one additional character can be added to t.

// Ex: Given the following strings...

// s = "foobar", t = "barfoot", return 't'
// s = "ide", t = "idea", return 'a'
// s = "coding", t "ingcod", return ''

#include<bits/stdc++.h>
#define ll long long
#define M 1000000007
#define u_set unordered_set
#define testfor(T) ll T; cin>>T; while(T--)
using namespace std;
void quickstart()
{
#ifndef ONLINE_JUDGE
	freopen("input.txt", "r", stdin);
	freopen("output.txt", "w", stdout);
#endif
	ios_base::sync_with_stdio(0);
}
int main()
{
	quickstart();
	string s, t;
	cin >> s >> t;
	int *arr = new int[256]();
	for (int i = 0; i < s.length(); i++) {
		arr[s[i]] += 1;
	}

	string ans = "";

	for (int i = 0; i < t.length(); i++) {
		arr[t[i]] -= 1;
		if (arr[t[i]] < 0) {
			ans = t[i];
			break;
		}
	}
	cout << ans << endl;
	return 0;
}